### ISSUE TITLE
Cars drive into the oncoming lane

### ISSUE THREAD

**Issue by MiroslavShard** [SunnyValleyStudio/Simple-Traffic-System-Unity-2020#1]
Cars pass intersections in the opposite lane if there are a lot of intersections. The problem is confirmed in the last 19 package.

https://user-images.githubusercontent.com/50916259/115969348-2f4f8880-a545-11eb-82ec-dfd2abbb6a30.mp4

**Comment by PetterSunnyVR** [comment]
Check out this video fix https://youtu.be/dRp2mceO-z4 . Sorry its not on github - I forgot to upload it!

**Comment by MiroslavShard** [comment]
Oh, I'm sorry. Thank you for your tutorials!
